@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "com.gof.design.creational.abstractFactory.snack.burger.Interface.Burger",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_102526 { 
   	label=gof
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_683207982 { 
   	label=design
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   AlooTikkiBurger1279112020[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)AlooTikkiBurger</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addIngredient()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

BaseBurger1279112020[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)BaseBurger</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addIngredient()</TD></TR>
<TR><TD ALIGN="LEFT" >+ prepareSnack()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

BasePizza305776271[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)BasePizza</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addIngredient()</TD></TR>
<TR><TD ALIGN="LEFT" >+ prepareSnack()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Burger761969065[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(I)Burger</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addIngredient()</TD></TR>
<TR><TD ALIGN="LEFT" >+ getBase(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ getSize(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ prepareSnack()</TD></TR>
<TR><TD ALIGN="LEFT" >+ setBase()</TD></TR>
<TR><TD ALIGN="LEFT" >+ setSize()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#F1E5FD"
];

CheesePizza305776271[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CheesePizza</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   baseType: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   size: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addIngredient()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ChickenBurger1279112020[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ChickenBurger</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addIngredient()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

PepperoniPizza305776271[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)PepperoniPizza</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   baseType: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   size: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addIngredient()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

VeggieBurger1279112020[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)VeggieBurger</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addIngredient()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

VeggiePizza305776271[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)VeggiePizza</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   baseType: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   size: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addIngredient()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
BaseBurger1279112020 -> AlooTikkiBurger1279112020[arrowhead=none, arrowtail=empty, dir=both];
BaseBurger1279112020 -> ChickenBurger1279112020[arrowhead=none, arrowtail=empty, dir=both];
BaseBurger1279112020 -> VeggieBurger1279112020[arrowhead=none, arrowtail=empty, dir=both];
BasePizza305776271 -> CheesePizza305776271[arrowhead=none, arrowtail=empty, dir=both];
BasePizza305776271 -> PepperoniPizza305776271[arrowhead=none, arrowtail=empty, dir=both];
BasePizza305776271 -> VeggiePizza305776271[arrowhead=none, arrowtail=empty, dir=both];
Burger761969065 -> BaseBurger1279112020[arrowhead=none, arrowtail=empty, dir=both];
Burger761969065 -> BasePizza305776271[arrowhead=none];
    
}
@enduml